### ISSUE TITLE
Igazság szerint most teljesen elvesztem ebben a PR-ben. Kérem segítséged illetve javaslatod egy kisebb rövidebb összeállításban ami helyes is az enyémmel ellentétben

### ISSUE THREAD

**Issue by Michelle9979** [paypal/paypal-messaging-components#297]
Igazság szerint most teljesen elvesztem ebben a PR-ben. Kérem segítséged illetve javaslatod egy kisebb rövidebb összeállításban ami helyes is az enyémmel ellentétben 

_Originally posted by @Jankyboy in https://github.com/plutov/paypal/pull/172#issuecomment-697753119_

**Comment by Michelle9979** [comment]
Thanks

**Comment by jasros** [comment]
seems to be unrelated to this repo, closing

**Comment by Michelle9979** [comment]
Thanks
