### ISSUE TITLE
`npm run dev:snapshot` isnt a script

### ISSUE THREAD

**Issue by lancemccluskey** [paypal/paypal-messaging-components#464]
On the README [here](https://github.com/paypal/paypal-messaging-components#functional), the npm script `dev:snapshot` is mentioned, but I dont see it anywhere in `package.json` on the `develop` branch. Is this intentional or should the readme be updated?

**Comment by merlinpatt** [comment]
Yes, the README needs to be updated. You can now run `npm run dev:standalone` instead to generate the static pages for the tests
