### ISSUE TITLE
Logo position does not apply to data-pp-style-logo-type=alternative

### ISSUE THREAD

**Issue by fascinosum** [paypal/paypal-messaging-components#526]
Hello everyone,

the following configuration does not work as expected 
```
<script src="https://www.paypal.com/sdk/js?client-id=sb&locale=en_US&currency=USD&components=messages"
    ></script>
<div data-pp-message=""
     data-pp-amount="50"
     data-pp-placement="product"
     data-pp-style-layout="text"
     data-pp-style-logo-type="alternative"
     data-pp-style-logo-position="top"
></div>
```

According to the [official documentation](https://developer.paypal.com/docs/business/pay-later/us/integrate/customize-messages/#lightweight-text-based-messages) this should work. 
However, this works if it's not "PP" monogram but "PP Credit" logo

**Comment by yeul** [comment]
Hi there, this is actually expected behavior as the alternative logo (PP monogram) only supports logo position left. Let me know if you have any other questions!

**Comment by fascinosum** [comment]
thank you, @yeul for the explanation. That sounds reasonable. Does it make sense to reflect this in the documentation?

**Comment by yeul** [comment]
Yes @fascinosum, there are absolutely plans on our roadmap to improve our documentation with regards to both content and clarity. Thank you for bringing up your concern, though, as it helps us zero in on places to improve. Much appreciated!
