### ISSUE TITLE
Feature Request: Adding notes / comments when making payments using paypalme link 

### ISSUE THREAD

**Issue by ssnirgudkar** [paypal/paypal-messaging-components#683]
Hello Paypal team, 
When making a payment via the paypalme link , there is no provision to add notes/comments while making the payment. We are part of our school PTSO, and we use paypal for all the donations (different categories and we need to track donations under each). We cannot expect all parents to have a paypal account and hence are using the paypalme link. However, without the notes section available , we have no way to know what the donations are for. If a user had a paypal account, they can use that to make donations and then add notes to indicate what cause the donations are for. But if they don't, then it's a problem. The only alternative is to create multiple accounts for each donation which adds complications for maintenance / monitoring etc. Can you please add the feature to be able to add notes while making payments via paypalme link?

**Comment by grablack** [comment]
Hi, @ssnirgudkar 
I'll reach out to the PayPal.Me team and update you when I hear back.

**Comment by grablack** [comment]
The request has been received. I will be closing this issue now.
