### ISSUE TITLE
Accessibility Issue for Installment Payments Modal on Safari

### ISSUE THREAD

**Issue by Parisakho** [paypal/paypal-messaging-components#995]
For https://www.lampsplus.com/ when the Paypal information pop-up window for installment payments appears on PDPs, screen readers remain focused on the content of the underlying page, making the pop-up invisible to screen reader users.

Issue is valid on: 
Mobile / Safari
Desktop / Safari

STEPS TO REPRODUCE

1. Navigate to a Lamps Plus [PDP ](https://www.lampsplus.com/products/possini-euro-carrine-38-and-one-half-inch-black-and-gold-kitchen-island-pendant__71f57.html)
2. Click to open the PayPal information modal
![image](https://github.com/paypal/paypal-messaging-components/assets/147004375/29c051c8-b112-46a2-921e-84351d31d8b6)

3. Observer the screenreader performance

**Comment by grablack** [comment]
Hi Parisakho,
We are actively working on addressing the issue. I'll update this issue when it is resolved.

Thanks

**Comment by Parisakho** [comment]
Thank you!

**Comment by grablack** [comment]
The changes are live now so we're going to close this issue. Thanks again!
